[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x666666"
blue = "0x6477fe"
cyan = "0x5ffdff"
green = "0x5ff967"
magenta = "0xff76ff"
red = "0xff6d67"
white = "0xffffff"
yellow = "0xfefb67"

[colors.normal]
black = "0x000000"
blue = "0x504ffe"
cyan = "0x00c5c7"
green = "0x00c200"
magenta = "0xc930c7"
red = "0xc91b00"
white = "0xeaeaea"
yellow = "0xc7c400"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[font]
size = 13.0

[font.normal]
family = "Select Mono"
style = "Italic"

[font.bold]
family = "Fantasque Sans Mono"

[font.italic]
family = "Fantasque Sans Mono"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
